using System.Collections.Generic;
using System.Globalization;
using System.Linq;

namespace ManufacturingCostManagement.Web.Localization
{
    public static class AppText
    {
        public static readonly string[] SupportedCultures = { "en", "vi" };

        private static readonly Dictionary<string, Dictionary<string, string>> _dict = new()
        {
            ["en"] = new Dictionary<string, string>
            {
                // ---- Brand / Footer ----
                ["App.Brand"] = "MfgCost",
                ["App.Title"] = "Manufacturing Cost Management",
                ["App.Tagline"] = "Production cost management by department",
                ["Footer.Copyright"] = "© 2026 Manufacturing Cost Management",

                // ---- Nav ----
                ["Nav.Dashboard"] = "Dashboard",
                ["Nav.Production"] = "Production",
                ["Nav.Products"] = "Products",
                ["Nav.Materials"] = "Materials",
                ["Nav.Suppliers"] = "Suppliers",
                ["Nav.Departments"] = "Departments",
                ["Nav.Reports"] = "Reports",
                ["Nav.ProductCostAnalysis"] = "Product Cost Analysis",
                ["Nav.CostByDepartment"] = "Cost by Department",
                ["Nav.LowStock"] = "Low Stock Materials",
                ["Nav.UserManagement"] = "User Management",
                ["Nav.PermissionsConfig"] = "Role Permissions",
                ["Nav.Administration"] = "Administration",
                ["Nav.Docs"] = "Docs",
                ["Nav.Language"] = "Language",
                ["Nav.SignedInAs"] = "Signed in as",
                ["Nav.ChangePassword"] = "Change Password",
                ["Nav.SignOut"] = "Sign out",

                // ---- Common buttons / labels ----
                ["Common.Save"] = "Save",
                ["Common.SaveChanges"] = "Save Changes",
                ["Common.Cancel"] = "Cancel",
                ["Common.Edit"] = "Edit",
                ["Common.Delete"] = "Delete",
                ["Common.View"] = "View",
                ["Common.Back"] = "Back",
                ["Common.Search"] = "Search",
                ["Common.New"] = "New",
                ["Common.Create"] = "Create",
                ["Common.Remove"] = "Remove",
                ["Common.Add"] = "Add",
                ["Common.Reset"] = "Reset",
                ["Common.Code"] = "Code",
                ["Common.Name"] = "Name",
                ["Common.Status"] = "Status",
                ["Common.Date"] = "Date",
                ["Common.Total"] = "Total",
                ["Common.Actions"] = "Actions",
                ["Common.Description"] = "Description",
                ["Common.Notes"] = "Notes",
                ["Common.NoData"] = "No records found",
                ["Common.ConfirmDelete"] = "Delete this record?",
                ["Common.Active"] = "Active",
                ["Common.Inactive"] = "Inactive",
                ["Common.Pending"] = "Pending",
                ["Common.InProgress"] = "In Progress",
                ["Common.Completed"] = "Completed",
                ["Common.Cancelled"] = "Cancelled",
                ["Common.Of"] = "of",
                ["Common.Page"] = "page",
                ["Common.TotalRecords"] = "total records",
                ["Common.NotAssigned"] = "Not assigned",
                ["Common.Filter"] = "Filter",
                ["Common.ClearFilters"] = "Clear",
                ["Common.AllOption"] = "— All —",
                ["Common.LowStockOnly"] = "Low stock only",

                // ---- Login ----
                ["Login.Headline"] = "Manufacturing<br/>Cost Management",
                ["Login.Sub"] = "Track material, labor, and overhead costs across every department in real time.",
                ["Login.Feature1"] = "Real-time cost calculation from Bill of Materials",
                ["Login.Feature2"] = "Department-level cost breakdown and reporting",
                ["Login.Feature3"] = "Role-based access — Admin / Manager / Accountant",
                ["Login.Feature4"] = "Production order tracking with profit margin analytics",
                ["Login.Welcome"] = "Welcome back",
                ["Login.Subtitle"] = "Please sign in to your account to continue.",
                ["Login.Username"] = "Username",
                ["Login.UsernamePlaceholder"] = "Enter your username",
                ["Login.Password"] = "Password",
                ["Login.PasswordPlaceholder"] = "Enter your password",
                ["Login.RememberMe"] = "Keep me signed in",
                ["Login.SignInBtn"] = "Sign in",
                ["Login.InvalidCredentials"] = "Invalid username or password",

                // ---- Login Team Section ----
                ["Team.Title"] = "Project Team — Manufacturing Cost Management",
                ["Team.Meta"] = "Project team members",
                ["Team.SttLabel"] = "No.",
                ["Team.LeadSuffix"] = "Lead Developer",
                ["Team.Role.Research"] = "Research & Analysis",
                ["Team.Role.Design"] = "Design & Data Storage",
                ["Team.Role.Lead"] = "★ Implementation Lead",

                ["Team.Phuong.Name"] = "Nguyễn Ngọc Hà Phương",
                ["Team.Phuong.Task1"] = "Survey production cost calculation processes",
                ["Team.Phuong.Task2"] = "Analyze business requirements & user stories",
                ["Team.Phuong.Task3"] = "Research material, labor & overhead cost formulas",
                ["Team.Phuong.Task4"] = "Write analysis documents & reports",

                ["Team.Ly.Name"] = "Nguyễn Hương Thảo Ly",
                ["Team.Ly.Task1"] = "Design UI/UX for the main screens",
                ["Team.Ly.Task2"] = "Design database schema & product storage",
                ["Team.Ly.Task3"] = "Draw ERD and Data Flow Diagrams (DFD)",
                ["Team.Ly.Task4"] = "Prepare sample data for testing",

                ["Team.Huyen.Name"] = "Nguyễn Thị Huyền",
                ["Team.Huyen.Task1"] = "Implement the entire system (BLL, DAL, Web)",
                ["Team.Huyen.Task2"] = "Build the cost-calculation module & reports",
                ["Team.Huyen.Task3"] = "Implement auth, permissions & multilingual UI",
                ["Team.Huyen.Task4"] = "Integrate database, Docker & system deployment",

                // ---- Dashboard ----
                ["Dashboard.Title"] = "Production Overview",
                ["Dashboard.Subtitle"] = "Real-time KPIs across material, labor and overhead costs",
                ["Dashboard.AsOf"] = "As of",
                ["Dashboard.Products"] = "Products",
                ["Dashboard.ProductsSub"] = "total items",
                ["Dashboard.Materials"] = "Materials",
                ["Dashboard.LowStockCount"] = "{0} low stock",
                ["Dashboard.Suppliers"] = "Suppliers",
                ["Dashboard.SuppliersSub"] = "active vendors",
                ["Dashboard.ProductionOrders"] = "Production Orders",
                ["Dashboard.InProgressCount"] = "{0} in progress",
                ["Dashboard.MaterialCost"] = "Material Cost",
                ["Dashboard.LaborCost"] = "Labor Cost",
                ["Dashboard.OverheadCost"] = "Overhead Cost",
                ["Dashboard.TotalCost"] = "Total Production Cost",
                ["Dashboard.OfTotal"] = "% of total",
                ["Dashboard.Baseline"] = "100% baseline",
                ["Dashboard.MonthlyChartTitle"] = "Monthly Production Cost",
                ["Dashboard.MonthlyChartSub"] = "Material / Labor / Overhead breakdown (last 12 months)",
                ["Dashboard.TopProductsTitle"] = "Top 5 Costly Products",
                ["Dashboard.TopProductsSub"] = "By total production cost",
                ["Dashboard.StatusTitle"] = "Production Status",
                ["Dashboard.StatusSub"] = "{0} total orders",
                ["Dashboard.TopDetailsTitle"] = "Top Costly Products — Details",
                ["Dashboard.FullAnalysis"] = "Full analysis →",
                ["Dashboard.OrdersCol"] = "Orders",
                ["Dashboard.TotalCostCol"] = "Total Cost (VND)",
                ["Dashboard.Product"] = "Product",

                // ---- Page headers / list pages ----
                ["Page.NewSuffix"] = "New",
                ["Page.Edit"] = "Edit",
                ["Page.Details"] = "Details",

                ["Suppliers.Title"] = "Suppliers",
                ["Suppliers.Subtitle"] = "Manage raw-material vendors and contacts",
                ["Suppliers.NewBtn"] = "+ New Supplier",
                ["Suppliers.NewTitle"] = "New Supplier",
                ["Suppliers.NewSub"] = "Add a raw-material vendor to the system",
                ["Suppliers.EditTitle"] = "Edit Supplier",
                ["Suppliers.DetailsSub"] = "Supplier profile",
                ["Suppliers.ContactPerson"] = "Contact Person",
                ["Suppliers.Phone"] = "Phone",
                ["Suppliers.Email"] = "Email",
                ["Suppliers.Address"] = "Address",
                ["Suppliers.Contact"] = "Contact",
                ["Suppliers.Registered"] = "Registered",
                ["Suppliers.SaveBtn"] = "Save Supplier",

                ["Materials.Title"] = "Materials",
                ["Materials.Subtitle"] = "Raw material inventory and reorder thresholds",
                ["Materials.NewBtn"] = "+ New Material",
                ["Materials.NewTitle"] = "New Material",
                ["Materials.NewSub"] = "Add a raw material to inventory",
                ["Materials.EditTitle"] = "Edit Material",
                ["Materials.Supplier"] = "Supplier",
                ["Materials.Unit"] = "Unit",
                ["Materials.UnitCost"] = "Unit Cost",
                ["Materials.Stock"] = "Stock",
                ["Materials.Reorder"] = "Reorder",
                ["Materials.ReorderLevel"] = "Reorder Level",
                ["Materials.StockQty"] = "Stock Qty",
                ["Materials.SaveBtn"] = "Save Material",
                ["Materials.LowStockTitle"] = "Low Stock Materials",
                ["Materials.LowStockSub"] = "Materials at or below reorder level — purchase order recommended",
                ["Materials.BackToMaterials"] = "← Back to Materials",
                ["Materials.NoLowStock"] = "✓ No low-stock materials",

                ["Products.Title"] = "Products",
                ["Products.Subtitle"] = "Finished goods catalog with bill-of-materials",
                ["Products.NewBtn"] = "+ New Product",
                ["Products.NewTitle"] = "New Product",
                ["Products.NewSub"] = "Add a finished good to the catalog",
                ["Products.EditTitle"] = "Edit Product",
                ["Products.Category"] = "Category",
                ["Products.Unit"] = "Unit",
                ["Products.SellingPrice"] = "Selling Price",
                ["Products.MaterialCost"] = "Material Cost",
                ["Products.GrossMargin"] = "Gross Margin",
                ["Products.ViewBom"] = "View / BOM",
                ["Products.BomTitle"] = "Bill of Materials",
                ["Products.BomSub"] = "Materials required per unit of product",
                ["Products.AddMaterial"] = "+ Add Material",
                ["Products.AddBomTitle"] = "Add Material to BOM",
                ["Products.Material"] = "Material",
                ["Products.Qty"] = "Qty Required",
                ["Products.QtyPerUnit"] = "Quantity per unit",
                ["Products.Subtotal"] = "Subtotal",
                ["Products.TotalMaterialCost"] = "Total Material Cost per unit",
                ["Products.NoBom"] = "No materials in BOM",
                ["Products.SaveBtn"] = "Save Product",
                ["Products.AddToBom"] = "Add to BOM",

                ["Production.Title"] = "Production Orders",
                ["Production.Subtitle"] = "Track manufacturing runs with cost breakdown per order",
                ["Production.NewBtn"] = "+ New Order",
                ["Production.NewTitle"] = "New Production Order",
                ["Production.NewSub"] = "Schedule a manufacturing run",
                ["Production.EditTitle"] = "Edit Production Order",
                ["Production.OrderCode"] = "Order Code",
                ["Production.Product"] = "Product",
                ["Production.Department"] = "Department",
                ["Production.Quantity"] = "Quantity",
                ["Production.StartDate"] = "Start Date",
                ["Production.EndDate"] = "End Date",
                ["Production.OrderInfo"] = "Order Information",
                ["Production.CostBreakdown"] = "Cost Breakdown",
                ["Production.LaborEntries"] = "Labor Entries",
                ["Production.OverheadEntries"] = "Overhead Entries",
                ["Production.AddLabor"] = "Add Labor Cost",
                ["Production.AddOverhead"] = "Add Overhead Cost",
                ["Production.Recalculate"] = "↻ Recalculate",
                ["Production.MarkComplete"] = "✓ Mark Complete",
                ["Production.Worker"] = "Worker",
                ["Production.Dept"] = "Dept",
                ["Production.Hours"] = "Hours",
                ["Production.Rate"] = "Rate",
                ["Production.Type"] = "Type",
                ["Production.Amount"] = "Amount",
                ["Production.HoursWorked"] = "Hours Worked",
                ["Production.HourlyRate"] = "Hourly Rate",
                ["Production.WorkerName"] = "Worker Name",
                ["Production.LaborSub"] = "Worker hours and hourly rate for this production order",
                ["Production.OverheadSub"] = "Manufacturing overhead allocated to this production order",
                ["Production.Entries"] = "entries",
                ["Production.Units"] = "units",
                ["Production.SaveLabor"] = "Save Labor Cost",
                ["Production.SaveOverhead"] = "Save Overhead Cost",
                ["Production.CreateBtn"] = "Create Order",

                ["Departments.Title"] = "Departments",
                ["Departments.Subtitle"] = "Production departments — track costs per organizational unit",
                ["Departments.NewBtn"] = "+ New Department",
                ["Departments.NewTitle"] = "New Department",
                ["Departments.NewSub"] = "Add a new production department",
                ["Departments.EditTitle"] = "Edit Department",
                ["Departments.Manager"] = "Manager",
                ["Departments.SaveBtn"] = "Save Department",

                ["Users.Title"] = "Users",
                ["Users.Subtitle"] = "Manage accounts and role-based access",
                ["Users.NewBtn"] = "+ New User",
                ["Users.Username"] = "Username",
                ["Users.FullName"] = "Full Name",
                ["Users.Email"] = "Email",
                ["Users.Role"] = "Role",
                ["Users.AccountInfo"] = "Account Information",
                ["Users.ResetPassword"] = "Reset Password",
                ["Users.NewPasswordPlaceholder"] = "New password (min 6 chars)",
                ["Users.CreateTitle"] = "Create New User",
                ["Users.CreateSub"] = "Add a user with role-based access",
                ["Users.CreateBtn"] = "Create User",

                ["Account.ChangePasswordTitle"] = "Change Password",
                ["Account.ChangePasswordSub"] = "Update your account password",
                ["Account.CurrentPassword"] = "Current Password",
                ["Account.NewPassword"] = "New Password",
                ["Account.ConfirmPassword"] = "Confirm New Password",
                ["Account.UpdatePassword"] = "Update Password",
                ["Account.AccessDenied"] = "Access Denied",
                ["Account.AccessDeniedSub"] = "You do not have permission to access this resource.",

                ["Reports.CostBreakdownTitle"] = "Product Cost Breakdown",
                ["Reports.CostBreakdownSub"] = "Per-unit cost decomposition with profit margin analysis",
                ["Reports.MaterialPerUnit"] = "Material/unit",
                ["Reports.AvgLaborPerUnit"] = "Avg Labor/unit",
                ["Reports.AvgOverheadPerUnit"] = "Avg Overhead/unit",
                ["Reports.TotalCostCol"] = "Total Cost",
                ["Reports.SellingPriceCol"] = "Selling Price",
                ["Reports.Profit"] = "Profit",
                ["Reports.Margin"] = "Margin %",
                ["Reports.DeptCostTitle"] = "Cost by Department",
                ["Reports.DeptCostSub"] = "Production cost by department — aggregated material, labor and overhead per department",
                ["Reports.DeptTable"] = "Department Cost Table",
                ["Reports.DeptChartTitle"] = "Department cost share",
                ["Reports.DeptChartSub"] = "Stacked cost components per department",
                ["Reports.Department"] = "Department",
                ["Reports.BackDashboard"] = "← Dashboard",

                ["Permissions.Title"] = "Role Permissions",
                ["Permissions.Subtitle"] = "Configure which actions each role can perform",
                ["Permissions.MatrixTitle"] = "Permission Matrix",
                ["Permissions.MatrixSub"] = "Check a box to grant; Admin has full access by default",
                ["Permissions.PermissionCol"] = "Permission",
                ["Permissions.NoteTitle"] = "Note:",
                ["Permissions.NoteBody"] = "Users must sign out and back in for permission changes to take effect on their sessions.",

                ["Docs.Title"] = "Documentation",
                ["Docs.Subtitle"] = "Feature overview and how to use the Manufacturing Cost Management app",
                ["Docs.Overview"] = "Overview",
                ["Docs.OverviewBody"] = "MfgCost is a 3-layer ASP.NET Core MVC application that tracks production costs by department — including direct materials, labor, and manufacturing overhead — for every production order. Costs roll up to dashboards, per-product profit analysis, and department-level reports so managers can see where the money is going in real time.",
                ["Docs.TocTitle"] = "On this page",
                ["Docs.Roles"] = "User Roles",
                ["Docs.RolesBody"] = "Four built-in roles control access. Admin can configure permissions on the Role Permissions page.",
                ["Docs.RoleAdmin"] = "Admin — full access to everything, including user management and role permissions",
                ["Docs.RoleManager"] = "Manager — manages suppliers, materials, products, BOM, production orders, and departments",
                ["Docs.RoleAccountant"] = "Accountant — read access to everything plus can add labor and overhead cost entries",
                ["Docs.RoleEmployee"] = "Employee — read-only access to dashboards, products, and orders",

                ["Docs.Modules"] = "Core Modules",
                ["Docs.ModSuppliers"] = "Suppliers — vendor directory: name, contact person, phone, email, address",
                ["Docs.ModMaterials"] = "Materials — raw material inventory with unit cost, stock, reorder level, and supplier link. Filter by supplier or low-stock.",
                ["Docs.ModProducts"] = "Products — finished goods catalogue. Each product has a Bill of Materials (BOM) listing required raw materials per unit.",
                ["Docs.ModDepartments"] = "Departments — production departments (Assembly, Machining, Electronics, etc.) that own production orders and bear labor/overhead costs.",
                ["Docs.ModOrders"] = "Production Orders — each manufacturing run has a product, quantity, assigned department, status (Pending / In Progress / Completed / Cancelled), and a live cost breakdown.",
                ["Docs.ModLaborOH"] = "Labor & Overhead — accountants can attach labor entries (worker, hours, rate) and overhead entries (Electricity, Rent, Equipment, Maintenance, Other) to any production order.",

                ["Docs.Cost"] = "Cost Calculation",
                ["Docs.CostBody"] = "Total production cost for an order is the sum of three components:",
                ["Docs.CostMaterial"] = "Material = Σ (BOM quantity × material unit cost) × order quantity",
                ["Docs.CostLabor"] = "Labor = Σ (hours worked × hourly rate) for every labor entry on the order",
                ["Docs.CostOverhead"] = "Overhead = Σ (amount) for every overhead entry on the order",
                ["Docs.CostRecalc"] = "Click \"Recalculate\" on an order's detail page to refresh all totals (also runs automatically whenever a labor or overhead entry is added).",

                ["Docs.Reports"] = "Reports & Dashboard",
                ["Docs.ReportsDashboard"] = "Dashboard — KPIs (products / materials / suppliers / orders), cost breakdown cards, monthly stacked-bar chart, top-5 product doughnut, status doughnut",
                ["Docs.ReportsCostAnalysis"] = "Product Cost Analysis — per-unit material / labor / overhead cost decomposition with profit margin per product",
                ["Docs.ReportsDept"] = "Cost by Department — aggregated material / labor / overhead per department with a horizontal stacked chart",
                ["Docs.ReportsLowStock"] = "Low Stock — materials at or below their reorder level (purchase-order trigger list)",

                ["Docs.Features"] = "Additional Features",
                ["Docs.FeatSearch"] = "Search & Filter — every list page has a search box plus filter dropdowns (supplier, category, status, role, etc.) and preserves filter state across pagination",
                ["Docs.FeatLang"] = "Bilingual UI — switch between English and Vietnamese with the globe icon in the navbar. The choice is saved in a cookie for 1 year.",
                ["Docs.FeatPerm"] = "Configurable role permissions — Admin can toggle CRUD permissions per role on the Role Permissions page. Users must sign out and back in for changes to take effect.",
                ["Docs.FeatI18nPwd"] = "Self-service password change — every signed-in user can update their password from the profile dropdown",

                ["Docs.Defaults"] = "Default Accounts",
                ["Docs.DefaultsBody"] = "On a fresh install, three demo accounts are seeded:",

                ["Docs.Stack"] = "Tech Stack",
                ["Docs.StackBody"] = "ASP.NET Core 8 MVC · Entity Framework Core 8 · SQL Server (Azure SQL Edge in Docker) · Bootstrap 5 · Chart.js 4 · Bootstrap Icons · BCrypt for password hashing · Cookie-based authentication with role + permission claims",
            },
            ["vi"] = new Dictionary<string, string>
            {
                // ---- Brand / Footer ----
                ["App.Brand"] = "MfgCost",
                ["App.Title"] = "Quản Lý Chi Phí Sản Xuất",
                ["App.Tagline"] = "Quản lý chi phí sản xuất theo từng bộ phận",
                ["Footer.Copyright"] = "© 2026 Quản Lý Chi Phí Sản Xuất",

                // ---- Nav ----
                ["Nav.Dashboard"] = "Tổng quan",
                ["Nav.Production"] = "Sản xuất",
                ["Nav.Products"] = "Sản phẩm",
                ["Nav.Materials"] = "Nguyên vật liệu",
                ["Nav.Suppliers"] = "Nhà cung cấp",
                ["Nav.Departments"] = "Bộ phận",
                ["Nav.Reports"] = "Báo cáo",
                ["Nav.ProductCostAnalysis"] = "Phân tích chi phí sản phẩm",
                ["Nav.CostByDepartment"] = "Chi phí theo bộ phận",
                ["Nav.LowStock"] = "Nguyên liệu sắp hết",
                ["Nav.UserManagement"] = "Quản lý người dùng",
                ["Nav.PermissionsConfig"] = "Phân quyền vai trò",
                ["Nav.Administration"] = "Quản trị",
                ["Nav.Docs"] = "Tài liệu",
                ["Nav.Language"] = "Ngôn ngữ",
                ["Nav.SignedInAs"] = "Đăng nhập với tên",
                ["Nav.ChangePassword"] = "Đổi mật khẩu",
                ["Nav.SignOut"] = "Đăng xuất",

                // ---- Common ----
                ["Common.Save"] = "Lưu",
                ["Common.SaveChanges"] = "Lưu thay đổi",
                ["Common.Cancel"] = "Hủy",
                ["Common.Edit"] = "Sửa",
                ["Common.Delete"] = "Xóa",
                ["Common.View"] = "Xem",
                ["Common.Back"] = "Quay lại",
                ["Common.Search"] = "Tìm kiếm",
                ["Common.New"] = "Mới",
                ["Common.Create"] = "Tạo",
                ["Common.Remove"] = "Gỡ",
                ["Common.Add"] = "Thêm",
                ["Common.Reset"] = "Đặt lại",
                ["Common.Code"] = "Mã",
                ["Common.Name"] = "Tên",
                ["Common.Status"] = "Trạng thái",
                ["Common.Date"] = "Ngày",
                ["Common.Total"] = "Tổng",
                ["Common.Actions"] = "Hành động",
                ["Common.Description"] = "Mô tả",
                ["Common.Notes"] = "Ghi chú",
                ["Common.NoData"] = "Không tìm thấy dữ liệu",
                ["Common.ConfirmDelete"] = "Xóa bản ghi này?",
                ["Common.Active"] = "Hoạt động",
                ["Common.Inactive"] = "Không hoạt động",
                ["Common.Pending"] = "Chờ xử lý",
                ["Common.InProgress"] = "Đang xử lý",
                ["Common.Completed"] = "Hoàn thành",
                ["Common.Cancelled"] = "Đã hủy",
                ["Common.Of"] = "trên",
                ["Common.Page"] = "trang",
                ["Common.TotalRecords"] = "bản ghi",
                ["Common.NotAssigned"] = "Chưa gán",
                ["Common.Filter"] = "Lọc",
                ["Common.ClearFilters"] = "Xóa bộ lọc",
                ["Common.AllOption"] = "— Tất cả —",
                ["Common.LowStockOnly"] = "Chỉ hiển thị sắp hết",

                // ---- Login ----
                ["Login.Headline"] = "Quản Lý<br/>Chi Phí Sản Xuất",
                ["Login.Sub"] = "Theo dõi chi phí nguyên vật liệu, nhân công và sản xuất chung theo thời gian thực ở mọi bộ phận.",
                ["Login.Feature1"] = "Tính toán chi phí thời gian thực từ định mức nguyên vật liệu",
                ["Login.Feature2"] = "Phân tích chi phí và báo cáo theo từng bộ phận",
                ["Login.Feature3"] = "Phân quyền theo vai trò — Admin / Quản lý / Kế toán",
                ["Login.Feature4"] = "Theo dõi đơn sản xuất với phân tích lợi nhuận",
                ["Login.Welcome"] = "Chào mừng quay lại",
                ["Login.Subtitle"] = "Vui lòng đăng nhập để tiếp tục.",
                ["Login.Username"] = "Tên đăng nhập",
                ["Login.UsernamePlaceholder"] = "Nhập tên đăng nhập",
                ["Login.Password"] = "Mật khẩu",
                ["Login.PasswordPlaceholder"] = "Nhập mật khẩu",
                ["Login.RememberMe"] = "Ghi nhớ đăng nhập",
                ["Login.SignInBtn"] = "Đăng nhập",
                ["Login.InvalidCredentials"] = "Tên đăng nhập hoặc mật khẩu không đúng",

                // ---- Login Team Section ----
                ["Team.Title"] = "Nhóm dự án — Quản Lý Chi Phí Sản Xuất",
                ["Team.Meta"] = "Nhóm thực hiện đồ án",
                ["Team.SttLabel"] = "STT",
                ["Team.LeadSuffix"] = "Trưởng nhóm lập trình",
                ["Team.Role.Research"] = "Nghiên cứu & Phân tích",
                ["Team.Role.Design"] = "Thiết kế & Lưu trữ dữ liệu",
                ["Team.Role.Lead"] = "★ Trưởng nhóm triển khai",

                ["Team.Phuong.Name"] = "Nguyễn Ngọc Hà Phương",
                ["Team.Phuong.Task1"] = "Khảo sát quy trình tính giá thành sản xuất",
                ["Team.Phuong.Task2"] = "Phân tích yêu cầu nghiệp vụ & user stories",
                ["Team.Phuong.Task3"] = "Nghiên cứu công thức chi phí NVL, nhân công, SX chung",
                ["Team.Phuong.Task4"] = "Viết tài liệu phân tích & báo cáo",

                ["Team.Ly.Name"] = "Nguyễn Hương Thảo Ly",
                ["Team.Ly.Task1"] = "Thiết kế UI/UX cho các màn hình chính",
                ["Team.Ly.Task2"] = "Thiết kế lược đồ CSDL & product storage",
                ["Team.Ly.Task3"] = "Vẽ ERD, sơ đồ luồng dữ liệu (DFD)",
                ["Team.Ly.Task4"] = "Chuẩn bị dữ liệu mẫu cho kiểm thử",

                ["Team.Huyen.Name"] = "Nguyễn Thị Huyền",
                ["Team.Huyen.Task1"] = "Lập trình toàn bộ hệ thống (BLL, DAL, Web)",
                ["Team.Huyen.Task2"] = "Xây dựng module tính giá thành & báo cáo",
                ["Team.Huyen.Task3"] = "Triển khai xác thực, phân quyền, đa ngôn ngữ",
                ["Team.Huyen.Task4"] = "Tích hợp CSDL, Docker & deploy hệ thống",

                // ---- Dashboard ----
                ["Dashboard.Title"] = "Tổng quan sản xuất",
                ["Dashboard.Subtitle"] = "Chỉ số thời gian thực về chi phí nguyên vật liệu, nhân công và sản xuất chung",
                ["Dashboard.AsOf"] = "Cập nhật lúc",
                ["Dashboard.Products"] = "Sản phẩm",
                ["Dashboard.ProductsSub"] = "tổng số mặt hàng",
                ["Dashboard.Materials"] = "Nguyên vật liệu",
                ["Dashboard.LowStockCount"] = "{0} sắp hết",
                ["Dashboard.Suppliers"] = "Nhà cung cấp",
                ["Dashboard.SuppliersSub"] = "đối tác đang hoạt động",
                ["Dashboard.ProductionOrders"] = "Đơn sản xuất",
                ["Dashboard.InProgressCount"] = "{0} đang xử lý",
                ["Dashboard.MaterialCost"] = "Chi phí nguyên vật liệu",
                ["Dashboard.LaborCost"] = "Chi phí nhân công",
                ["Dashboard.OverheadCost"] = "Chi phí sản xuất chung",
                ["Dashboard.TotalCost"] = "Tổng chi phí sản xuất",
                ["Dashboard.OfTotal"] = "% của tổng",
                ["Dashboard.Baseline"] = "100% cơ sở",
                ["Dashboard.MonthlyChartTitle"] = "Chi phí sản xuất theo tháng",
                ["Dashboard.MonthlyChartSub"] = "Phân tích nguyên vật liệu / nhân công / sản xuất chung (12 tháng gần nhất)",
                ["Dashboard.TopProductsTitle"] = "Top 5 sản phẩm chi phí cao",
                ["Dashboard.TopProductsSub"] = "Theo tổng chi phí sản xuất",
                ["Dashboard.StatusTitle"] = "Trạng thái sản xuất",
                ["Dashboard.StatusSub"] = "Tổng {0} đơn hàng",
                ["Dashboard.TopDetailsTitle"] = "Chi tiết sản phẩm chi phí cao",
                ["Dashboard.FullAnalysis"] = "Xem đầy đủ →",
                ["Dashboard.OrdersCol"] = "Đơn hàng",
                ["Dashboard.TotalCostCol"] = "Tổng chi phí (VND)",
                ["Dashboard.Product"] = "Sản phẩm",

                // ---- Page headers ----
                ["Page.NewSuffix"] = "Mới",
                ["Page.Edit"] = "Sửa",
                ["Page.Details"] = "Chi tiết",

                ["Suppliers.Title"] = "Nhà cung cấp",
                ["Suppliers.Subtitle"] = "Quản lý nhà cung cấp nguyên vật liệu và thông tin liên hệ",
                ["Suppliers.NewBtn"] = "+ Thêm nhà cung cấp",
                ["Suppliers.NewTitle"] = "Nhà cung cấp mới",
                ["Suppliers.NewSub"] = "Thêm nhà cung cấp nguyên vật liệu vào hệ thống",
                ["Suppliers.EditTitle"] = "Sửa nhà cung cấp",
                ["Suppliers.DetailsSub"] = "Hồ sơ nhà cung cấp",
                ["Suppliers.ContactPerson"] = "Người liên hệ",
                ["Suppliers.Phone"] = "Điện thoại",
                ["Suppliers.Email"] = "Email",
                ["Suppliers.Address"] = "Địa chỉ",
                ["Suppliers.Contact"] = "Liên hệ",
                ["Suppliers.Registered"] = "Đã đăng ký",
                ["Suppliers.SaveBtn"] = "Lưu nhà cung cấp",

                ["Materials.Title"] = "Nguyên vật liệu",
                ["Materials.Subtitle"] = "Tồn kho nguyên vật liệu và ngưỡng đặt hàng lại",
                ["Materials.NewBtn"] = "+ Thêm nguyên vật liệu",
                ["Materials.NewTitle"] = "Nguyên vật liệu mới",
                ["Materials.NewSub"] = "Thêm nguyên vật liệu vào kho",
                ["Materials.EditTitle"] = "Sửa nguyên vật liệu",
                ["Materials.Supplier"] = "Nhà cung cấp",
                ["Materials.Unit"] = "Đơn vị",
                ["Materials.UnitCost"] = "Giá đơn vị",
                ["Materials.Stock"] = "Tồn kho",
                ["Materials.Reorder"] = "Đặt lại",
                ["Materials.ReorderLevel"] = "Mức đặt lại",
                ["Materials.StockQty"] = "Số lượng tồn",
                ["Materials.SaveBtn"] = "Lưu nguyên vật liệu",
                ["Materials.LowStockTitle"] = "Nguyên liệu sắp hết",
                ["Materials.LowStockSub"] = "Nguyên vật liệu ở hoặc dưới mức đặt lại — cần đặt hàng",
                ["Materials.BackToMaterials"] = "← Quay lại Nguyên vật liệu",
                ["Materials.NoLowStock"] = "✓ Không có nguyên liệu sắp hết",

                ["Products.Title"] = "Sản phẩm",
                ["Products.Subtitle"] = "Danh mục thành phẩm với định mức nguyên vật liệu",
                ["Products.NewBtn"] = "+ Thêm sản phẩm",
                ["Products.NewTitle"] = "Sản phẩm mới",
                ["Products.NewSub"] = "Thêm thành phẩm vào danh mục",
                ["Products.EditTitle"] = "Sửa sản phẩm",
                ["Products.Category"] = "Danh mục",
                ["Products.Unit"] = "Đơn vị",
                ["Products.SellingPrice"] = "Giá bán",
                ["Products.MaterialCost"] = "Chi phí NVL",
                ["Products.GrossMargin"] = "Tỷ suất lợi nhuận",
                ["Products.ViewBom"] = "Xem / BOM",
                ["Products.BomTitle"] = "Định mức nguyên vật liệu",
                ["Products.BomSub"] = "Nguyên vật liệu cần cho mỗi đơn vị sản phẩm",
                ["Products.AddMaterial"] = "+ Thêm nguyên vật liệu",
                ["Products.AddBomTitle"] = "Thêm nguyên vật liệu vào BOM",
                ["Products.Material"] = "Nguyên vật liệu",
                ["Products.Qty"] = "Số lượng cần",
                ["Products.QtyPerUnit"] = "Số lượng / đơn vị",
                ["Products.Subtotal"] = "Thành tiền",
                ["Products.TotalMaterialCost"] = "Tổng chi phí NVL / đơn vị",
                ["Products.NoBom"] = "Chưa có nguyên vật liệu trong BOM",
                ["Products.SaveBtn"] = "Lưu sản phẩm",
                ["Products.AddToBom"] = "Thêm vào BOM",

                ["Production.Title"] = "Đơn sản xuất",
                ["Production.Subtitle"] = "Theo dõi đợt sản xuất với phân tích chi phí mỗi đơn",
                ["Production.NewBtn"] = "+ Đơn sản xuất mới",
                ["Production.NewTitle"] = "Đơn sản xuất mới",
                ["Production.NewSub"] = "Lên lịch một đợt sản xuất",
                ["Production.EditTitle"] = "Sửa đơn sản xuất",
                ["Production.OrderCode"] = "Mã đơn",
                ["Production.Product"] = "Sản phẩm",
                ["Production.Department"] = "Bộ phận",
                ["Production.Quantity"] = "Số lượng",
                ["Production.StartDate"] = "Ngày bắt đầu",
                ["Production.EndDate"] = "Ngày kết thúc",
                ["Production.OrderInfo"] = "Thông tin đơn hàng",
                ["Production.CostBreakdown"] = "Phân tích chi phí",
                ["Production.LaborEntries"] = "Mục nhân công",
                ["Production.OverheadEntries"] = "Mục sản xuất chung",
                ["Production.AddLabor"] = "Thêm chi phí nhân công",
                ["Production.AddOverhead"] = "Thêm chi phí sản xuất chung",
                ["Production.Recalculate"] = "↻ Tính lại",
                ["Production.MarkComplete"] = "✓ Đánh dấu hoàn thành",
                ["Production.Worker"] = "Công nhân",
                ["Production.Dept"] = "Bộ phận",
                ["Production.Hours"] = "Giờ",
                ["Production.Rate"] = "Đơn giá",
                ["Production.Type"] = "Loại",
                ["Production.Amount"] = "Số tiền",
                ["Production.HoursWorked"] = "Số giờ làm",
                ["Production.HourlyRate"] = "Đơn giá / giờ",
                ["Production.WorkerName"] = "Tên công nhân",
                ["Production.LaborSub"] = "Giờ công và đơn giá cho đơn sản xuất này",
                ["Production.OverheadSub"] = "Chi phí sản xuất chung phân bổ cho đơn này",
                ["Production.Entries"] = "mục",
                ["Production.Units"] = "đơn vị",
                ["Production.SaveLabor"] = "Lưu chi phí nhân công",
                ["Production.SaveOverhead"] = "Lưu chi phí sản xuất chung",
                ["Production.CreateBtn"] = "Tạo đơn hàng",

                ["Departments.Title"] = "Bộ phận",
                ["Departments.Subtitle"] = "Bộ phận sản xuất — theo dõi chi phí theo đơn vị tổ chức",
                ["Departments.NewBtn"] = "+ Thêm bộ phận",
                ["Departments.NewTitle"] = "Bộ phận mới",
                ["Departments.NewSub"] = "Thêm bộ phận sản xuất mới",
                ["Departments.EditTitle"] = "Sửa bộ phận",
                ["Departments.Manager"] = "Trưởng bộ phận",
                ["Departments.SaveBtn"] = "Lưu bộ phận",

                ["Users.Title"] = "Người dùng",
                ["Users.Subtitle"] = "Quản lý tài khoản và phân quyền vai trò",
                ["Users.NewBtn"] = "+ Người dùng mới",
                ["Users.Username"] = "Tên đăng nhập",
                ["Users.FullName"] = "Họ và tên",
                ["Users.Email"] = "Email",
                ["Users.Role"] = "Vai trò",
                ["Users.AccountInfo"] = "Thông tin tài khoản",
                ["Users.ResetPassword"] = "Đặt lại mật khẩu",
                ["Users.NewPasswordPlaceholder"] = "Mật khẩu mới (tối thiểu 6 ký tự)",
                ["Users.CreateTitle"] = "Tạo người dùng mới",
                ["Users.CreateSub"] = "Thêm người dùng với phân quyền vai trò",
                ["Users.CreateBtn"] = "Tạo người dùng",

                ["Account.ChangePasswordTitle"] = "Đổi mật khẩu",
                ["Account.ChangePasswordSub"] = "Cập nhật mật khẩu tài khoản",
                ["Account.CurrentPassword"] = "Mật khẩu hiện tại",
                ["Account.NewPassword"] = "Mật khẩu mới",
                ["Account.ConfirmPassword"] = "Xác nhận mật khẩu mới",
                ["Account.UpdatePassword"] = "Cập nhật mật khẩu",
                ["Account.AccessDenied"] = "Truy cập bị từ chối",
                ["Account.AccessDeniedSub"] = "Bạn không có quyền truy cập tài nguyên này.",

                ["Reports.CostBreakdownTitle"] = "Phân tích chi phí sản phẩm",
                ["Reports.CostBreakdownSub"] = "Phân tích chi phí theo đơn vị với phân tích biên lợi nhuận",
                ["Reports.MaterialPerUnit"] = "NVL / đơn vị",
                ["Reports.AvgLaborPerUnit"] = "TB nhân công / đơn vị",
                ["Reports.AvgOverheadPerUnit"] = "TB sản xuất chung / đơn vị",
                ["Reports.TotalCostCol"] = "Tổng chi phí",
                ["Reports.SellingPriceCol"] = "Giá bán",
                ["Reports.Profit"] = "Lợi nhuận",
                ["Reports.Margin"] = "Biên %",
                ["Reports.DeptCostTitle"] = "Chi phí theo bộ phận",
                ["Reports.DeptCostSub"] = "Chi phí sản xuất theo từng bộ phận — tổng hợp NVL, nhân công và sản xuất chung",
                ["Reports.DeptTable"] = "Bảng chi phí bộ phận",
                ["Reports.DeptChartTitle"] = "Tỷ lệ chi phí bộ phận",
                ["Reports.DeptChartSub"] = "Thành phần chi phí xếp chồng theo bộ phận",
                ["Reports.Department"] = "Bộ phận",
                ["Reports.BackDashboard"] = "← Tổng quan",

                ["Permissions.Title"] = "Phân quyền vai trò",
                ["Permissions.Subtitle"] = "Cấu hình hành động mỗi vai trò được phép thực hiện",
                ["Permissions.MatrixTitle"] = "Ma trận quyền",
                ["Permissions.MatrixSub"] = "Chọn ô để cấp quyền; Admin có toàn quyền mặc định",
                ["Permissions.PermissionCol"] = "Quyền",
                ["Permissions.NoteTitle"] = "Lưu ý:",
                ["Permissions.NoteBody"] = "Người dùng cần đăng xuất và đăng nhập lại để áp dụng thay đổi quyền.",

                ["Docs.Title"] = "Tài liệu",
                ["Docs.Subtitle"] = "Tổng quan tính năng và hướng dẫn sử dụng ứng dụng Quản lý chi phí sản xuất",
                ["Docs.Overview"] = "Tổng quan",
                ["Docs.OverviewBody"] = "MfgCost là ứng dụng ASP.NET Core MVC 3 lớp giúp theo dõi chi phí sản xuất theo từng bộ phận — bao gồm nguyên vật liệu trực tiếp, nhân công, và chi phí sản xuất chung — cho mỗi đơn sản xuất. Chi phí được tổng hợp lên bảng điều khiển, phân tích lợi nhuận theo sản phẩm, và báo cáo theo bộ phận để quản lý biết được dòng tiền theo thời gian thực.",
                ["Docs.TocTitle"] = "Mục lục",
                ["Docs.Roles"] = "Vai trò người dùng",
                ["Docs.RolesBody"] = "Bốn vai trò mặc định kiểm soát truy cập. Admin có thể cấu hình quyền tại trang Phân quyền vai trò.",
                ["Docs.RoleAdmin"] = "Admin — toàn quyền, bao gồm quản lý người dùng và phân quyền vai trò",
                ["Docs.RoleManager"] = "Quản lý — quản lý nhà cung cấp, nguyên vật liệu, sản phẩm, BOM, đơn sản xuất, bộ phận",
                ["Docs.RoleAccountant"] = "Kế toán — xem mọi mục và thêm chi phí nhân công, chi phí sản xuất chung",
                ["Docs.RoleEmployee"] = "Nhân viên — chỉ xem bảng điều khiển, sản phẩm và đơn hàng",

                ["Docs.Modules"] = "Mô-đun chính",
                ["Docs.ModSuppliers"] = "Nhà cung cấp — danh bạ đối tác: tên, người liên hệ, điện thoại, email, địa chỉ",
                ["Docs.ModMaterials"] = "Nguyên vật liệu — tồn kho với giá, số lượng, ngưỡng đặt lại, liên kết nhà cung cấp. Lọc theo nhà cung cấp hoặc trạng thái sắp hết.",
                ["Docs.ModProducts"] = "Sản phẩm — danh mục thành phẩm. Mỗi sản phẩm có một định mức nguyên vật liệu (BOM) liệt kê NVL cần dùng cho mỗi đơn vị.",
                ["Docs.ModDepartments"] = "Bộ phận — bộ phận sản xuất (Lắp ráp, Gia công, Điện tử, ...) sở hữu đơn sản xuất và gánh chi phí nhân công/sản xuất chung.",
                ["Docs.ModOrders"] = "Đơn sản xuất — mỗi đợt sản xuất có sản phẩm, số lượng, bộ phận đảm nhận, trạng thái (Chờ / Đang xử lý / Hoàn thành / Đã hủy), và phân tích chi phí trực tiếp.",
                ["Docs.ModLaborOH"] = "Nhân công & Sản xuất chung — kế toán có thể thêm mục nhân công (công nhân, giờ, đơn giá) và sản xuất chung (Điện, Thuê mặt bằng, Máy móc, Bảo trì, Khác) vào bất kỳ đơn sản xuất nào.",

                ["Docs.Cost"] = "Tính toán chi phí",
                ["Docs.CostBody"] = "Tổng chi phí sản xuất của một đơn hàng là tổng của ba thành phần:",
                ["Docs.CostMaterial"] = "Nguyên vật liệu = Σ (số lượng BOM × giá đơn vị NVL) × số lượng đơn",
                ["Docs.CostLabor"] = "Nhân công = Σ (số giờ làm × đơn giá giờ) cho mọi mục nhân công của đơn",
                ["Docs.CostOverhead"] = "Sản xuất chung = Σ (số tiền) cho mọi mục sản xuất chung của đơn",
                ["Docs.CostRecalc"] = "Nhấn \"Tính lại\" ở trang chi tiết đơn để cập nhật toàn bộ tổng (cũng tự động chạy mỗi khi thêm mục nhân công/sản xuất chung).",

                ["Docs.Reports"] = "Báo cáo & Bảng điều khiển",
                ["Docs.ReportsDashboard"] = "Bảng điều khiển — KPI (sản phẩm / NVL / nhà cung cấp / đơn hàng), thẻ phân tích chi phí, biểu đồ cột xếp chồng theo tháng, biểu đồ tròn top-5 sản phẩm, biểu đồ trạng thái",
                ["Docs.ReportsCostAnalysis"] = "Phân tích chi phí sản phẩm — phân rã chi phí NVL / nhân công / SX chung trên mỗi đơn vị kèm biên lợi nhuận",
                ["Docs.ReportsDept"] = "Chi phí theo bộ phận — tổng hợp NVL / nhân công / SX chung theo bộ phận với biểu đồ cột ngang xếp chồng",
                ["Docs.ReportsLowStock"] = "Nguyên liệu sắp hết — NVL ở hoặc dưới ngưỡng đặt lại (danh sách gợi ý đặt hàng)",

                ["Docs.Features"] = "Tính năng bổ sung",
                ["Docs.FeatSearch"] = "Tìm kiếm & Lọc — mọi trang danh sách đều có ô tìm kiếm và bộ lọc (nhà cung cấp, danh mục, trạng thái, vai trò...) đồng thời giữ trạng thái khi phân trang",
                ["Docs.FeatLang"] = "Giao diện song ngữ — chuyển đổi giữa tiếng Anh và tiếng Việt bằng biểu tượng quả địa cầu trên thanh điều hướng. Lựa chọn được lưu trong cookie 1 năm.",
                ["Docs.FeatPerm"] = "Phân quyền cấu hình được — Admin có thể bật/tắt quyền CRUD cho từng vai trò ở trang Phân quyền vai trò. Người dùng cần đăng xuất rồi đăng nhập lại để áp dụng.",
                ["Docs.FeatI18nPwd"] = "Tự đổi mật khẩu — mọi người dùng đã đăng nhập có thể đổi mật khẩu từ menu hồ sơ",

                ["Docs.Defaults"] = "Tài khoản mặc định",
                ["Docs.DefaultsBody"] = "Khi mới cài đặt, ba tài khoản demo được tạo sẵn:",

                ["Docs.Stack"] = "Công nghệ sử dụng",
                ["Docs.StackBody"] = "ASP.NET Core 8 MVC · Entity Framework Core 8 · SQL Server (Azure SQL Edge trong Docker) · Bootstrap 5 · Chart.js 4 · Bootstrap Icons · BCrypt cho mã hóa mật khẩu · Xác thực Cookie với claim vai trò và quyền",
            }
        };

        public static string Get(string key, string? culture = null)
        {
            culture ??= CultureInfo.CurrentUICulture.TwoLetterISOLanguageName;
            if (_dict.TryGetValue(culture, out var table) && table.TryGetValue(key, out var val)) return val;
            if (_dict["en"].TryGetValue(key, out var fallback)) return fallback;
            return key;
        }
    }
}
